In [1]:
import numpy as np

## Basic Functions

In [2]:
arr1 = np.array([2,4,6,1])
arr1

array([2, 4, 6, 1])

In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr1 = np.array([[2,4,6,8],
               [7,3,6,0]])
arr1

array([[2, 4, 6, 8],
       [7, 3, 6, 0]])

In [5]:
arr1.shape

(2, 4)

In [6]:
arr1.dtype

dtype('int32')

In [7]:
arr1.size

8

In [9]:
# custom dtype
arr1 = np.array([[2,4.6,6,8],
               [7,3,6,0]], dtype='int64')
arr1

array([[2, 4, 6, 8],
       [7, 3, 6, 0]], dtype=int64)

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((4,6), dtype='int64')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [13]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(6).dtype

dtype('float64')

In [15]:
np.empty((4,6))     # garbage value

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29060871e-306, 4.45057212e-308, 1.29060871e-306],
       [1.42419938e-306, 7.56603881e-307, 8.45603440e-307,
        3.56043054e-307, 1.60219306e-306, 6.23059726e-307],
       [1.06811422e-306, 3.56043054e-307, 1.37961641e-306,
        8.90071135e-308, 8.01097889e-307, 1.78020169e-306],
       [7.56601165e-307, 1.02359984e-306, 1.33510679e-306,
        2.22522597e-306, 1.33511018e-306, 2.31301135e-312]])

In [16]:
arr1 = np.array([[2,4,6,8],
               [7,3,6,0]])
arr1

array([[2, 4, 6, 8],
       [7, 3, 6, 0]])

In [17]:
arr1 * arr1     # not a matrix multliplication

array([[ 4, 16, 36, 64],
       [49,  9, 36,  0]])

In [18]:
arr1 + arr1 

array([[ 4,  8, 12, 16],
       [14,  6, 12,  0]])

In [19]:
arr1 - arr1 

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
arr1 / arr1 

C:\Users\Hammad Alam\AppData\Local\Temp\ipykernel_1924\3729122699.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr1 / arr1


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., nan]])

In [21]:
arr1 ** arr1 

array([[       4,      256,    46656, 16777216],
       [  823543,       27,    46656,        1]])

In [22]:
1/arr1

C:\Users\Hammad Alam\AppData\Local\Temp\ipykernel_1924\393800717.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr1


array([[0.5       , 0.25      , 0.16666667, 0.125     ],
       [0.14285714, 0.33333333, 0.16666667,        inf]])

## Slicing

In [27]:
arr = np.array([3,5,7,8,0,1])
arr

array([3, 5, 7, 8, 0, 1])

In [28]:
arrSliced = arr[4:6]
arrSliced

array([0, 1])

In [37]:
arrSliced[0] = 1
arrSliced

array([1, 1])

In [31]:
arr     # original array ko he change kardia

array([3, 5, 7, 8, 1, 1])

---
above problem can be avoid by using copy()

In [32]:
arr2 = np.array([3,5,7,8,0,1])
arr2

array([3, 5, 7, 8, 0, 1])

In [35]:
arr2Sliced = arr2[4:6].copy()
arr2Sliced

array([0, 1])

In [36]:
arr2Sliced[0] = 99
arr2Sliced

array([99,  1])

In [39]:
arr2        # now it has not changed

array([3, 5, 7, 8, 0, 1])

---

In [40]:
arr1 = np.array([[2,4,6,8],
               [7,3,6,0]])
arr1

array([[2, 4, 6, 8],
       [7, 3, 6, 0]])

In [41]:
# slicing of 2-D array
arr1[0,3]

8

In [43]:
# alternate way
arr1[0][2:4]

array([6, 8])