In [1]:
import numpy as np

In [6]:
a = np.array([[1,2,3],
                [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# axis of arrays
a.sum(axis=0)     # column wise

array([5, 7, 9])

In [8]:
a.sum(axis=1)     # row wise

array([ 6, 15])

---

In [13]:
b = np.array([[7,8,9],
            [2,8,0]])
b

array([[7, 8, 9],
       [2, 8, 0]])

In [16]:
# dot product  (2x3 with 3x2)
np.dot(a, b.transpose())

array([[ 50,  18],
       [122,  48]])

In [17]:
# cross product
np.cross(a, b)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

---

In [24]:
c = np.array([[7,6,9],
            [2,8,0]])
c

array([[7, 6, 9],
       [2, 8, 0]])

In [26]:
np.sort(c)      # sort on axis 1

array([[6, 7, 9],
       [0, 2, 8]])

In [27]:
np.sort(c, axis=0)      # sort on axis 0

array([[2, 6, 0],
       [7, 8, 9]])