In [1]:
import numpy as np

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [11]:
b = np.array([8,34,65,3,6,4,76,3,67,345,7,23,5,3,634,5,12,78])
# b = b.reshape((3,6))        # will reshape the array into 3 rows and 6 columns

In [12]:
b

array([  8,  34,  65,   3,   6,   4,  76,   3,  67, 345,   7,  23,   5,
         3, 634,   5,  12,  78])

In [14]:
np.argsort(b)   # iska output wo indices hain jo is array ko sort kardengi

array([ 3,  7, 13,  5, 15, 12,  4, 10,  0, 16, 11,  1,  2,  8,  6, 17,  9,
       14], dtype=int64)

In [15]:
np.argmin(b)    # sab say chotai value ki index position

3

In [16]:
np.argmax(b)    # sab say bari value ki index position

14

---
### argsort(), argmin(), argmax() after reshaping

In [18]:
b = b.reshape((6,3))
b

array([[  8,  34,  65],
       [  3,   6,   4],
       [ 76,   3,  67],
       [345,   7,  23],
       [  5,   3, 634],
       [  5,  12,  78]])

In [19]:
np.argsort(b)       # axis 1 pe sort indices ki values dega

array([[0, 1, 2],
       [0, 2, 1],
       [1, 2, 0],
       [1, 2, 0],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

In [21]:
np.argsort(b, axis=0)     # axis 1 pe sort indices ki values dega   

array([[1, 2, 1],
       [4, 4, 3],
       [5, 1, 0],
       [0, 3, 2],
       [2, 5, 5],
       [3, 0, 4]], dtype=int64)